[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.37/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino

platform_packages =
    platformio/framework-arduinoespressif32 @ https://github.com/espressif/arduino-esp32.git#3.3.7

; Match Arduino IDE Settings
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_upload.flash_size = 16MB
board_build.partitions = huge_app.csv

; PSRAM: OPI PSRAM setting
board_build.arduino.memory_type = qio_opi
board_upload.maximum_size = 16777216

monitor_speed = 115200

build_flags =
    ; USB CDC On Boot: "Enabled"
    -D ARDUINO_USB_CDC_ON_BOOT=1
    ; USB Mode: "Hardware CDC and JTAG"
    -D ARDUINO_USB_MODE=1
    ; Arduino Runs On: "Core 1" & Events Run On: "Core 1"
    -D ARDUINO_RUNNING_CORE=1
    -D ARDUINO_EVENT_RUNNING_CORE=1
    ; PSRAM enabled flag
    -D BOARD_HAS_PSRAM
    ; Your existing flags
    -D LV_LVGL_H_INCLUDE_SIMPLE
    -D LV_CONF_INCLUDE_SIMPLE
    -I knobby/

; Libraries: pin the exact libs/versions referenced in README.md
lib_deps =
  https://github.com/moononournation/Arduino_GFX.git#v1.6.5
  https://github.com/lvgl/lvgl.git#v8.4.0
  https://github.com/fbiego/CST816S.git#1.3.0
  https://github.com/esp-arduino-libs/ESP32_IO_Expander.git#v1.1.1
  https://github.com/esp-arduino-libs/ESP32_Display_Panel.git#v1.0.4
  https://github.com/esp-arduino-libs/esp-lib-utils.git#v0.2.2
  https://github.com/lewisxhe/SensorLib.git#v0.3.1

[platformio]
default_envs = esp32s3
src_dir = knobby